language: node_js
node_js:
  - '5'
before_install:
  - rm -rf node_modules
  - npm cache clean
  - npm install gulp
script:
  - npm install
  - ./node_modules/.bin/webdriver-manager update --standalone
  - ./node_modules/.bin/webdriver-manager start
  - npm test
